### ISSUE TITLE
Question regarding to secret-auto-rotation feature

### ISSUE THREAD

**Issue by qinxx108** [kubernetes-sigs/secrets-store-csi-driver#1076]
In the document:https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html 
This secret-auto-rotation feature is marked as alpha feature. I wonder how far this feature is production ready 

Thanks
Yijie

**Comment by aramase** [comment]
> This secret-auto-rotation feature is marked as alpha feature. I wonder how far this feature is production ready

The feature is marked alpha because we plan to replace the rotation implementation with [RequiresRepublish](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/585). This shouldn't change the behavior much for how to use rotation. The rotation feature has existed for close to 2 years now and is production ready.
