### ISSUE TITLE
Unable to get running on GKE

### ISSUE THREAD

**Issue by Leweyy** [kubernetes-sigs/secrets-store-csi-driver#1077]
**What steps did you take and what happened:**
Currently unable to get the CSI driver running on GKE. Installed 1.2.4 using kustomize files, noticed the pods were in a crashloopbackoff, checked the node-driver-registrar container and is seems its unable to connect to unix:///csi/csi.sock

**What did you expect to happen:**
Driver to run and liveliness probe to pass

**Anything else you would like to add:**

tried k8s 1.24.5-gke.600 with CSI versions 1.0.1, 1.1.0, 1.2.0 and 1.2.4
tried k8s v1.22.13-gke.1000 with CSI versions 1.0.1, 1.1.0, 1.2.0 and 1.2.4

node-driver-registrar logs
```I1019 17:04:35.345609       1 main.go:166] Version: v2.5.1
I1019 17:04:35.345684       1 main.go:167] Running node-driver-registrar in mode=registration
I1019 17:04:35.346386       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1019 17:04:35.346431       1 connection.go:154] Connecting to unix:///csi/csi.sock
W1019 17:04:45.347269       1 connection.go:173] Still connecting to unix:///csi/csi.sock
```

**Which provider are you using:**
GCP 

**Environment:**

- Secrets Store CSI Driver version: v1.2.4
- Kubernetes version: (use `kubectl version`): v1.22.13-gke.1000

**Comment by aramase** [comment]
Could you share the driver logs? You can get that by running `kubectl logs <pod name> -c secrets-store`

cc @tam7t

**Comment by aramase** [comment]
@Leweyy How are you deploying the driver? The install instructions are here: https://secrets-store-csi-driver.sigs.k8s.io/getting-started/installation.html

**Comment by Leweyy** [comment]
@aramase Apologies for wasting your time, looks like it was indeed an issue with the deployment, some resources were being left out

**Comment by phanhoaithuabc** [comment]
@Leweyy Can you share the solution? I have same issue like this:
`I0712 02:54:35.755452       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0712 02:54:35.756354       1 main.go:190] "starting manager\n"
I0712 02:54:35.849361       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:35.849430       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
I0712 02:54:37.008593       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:37.008632       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
I0712 02:54:37.514662       1 request.go:601] "Waited for 1.047725337s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/discovery.k8s.io/v1beta1?timeout=32s\n"
I0712 02:54:39.463049       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:39.463088       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:41.360598       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
I0712 02:54:45.000032       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:45.000065       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:46.360354       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:54:51.360924       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:54:56.361243       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
I0712 02:54:57.789768       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:54:57.789800       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:55:01.360698       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:55:06.360650       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:55:11.360435       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:55:16.359860       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
I0712 02:55:20.027473       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:55:20.027504       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
E0712 02:55:21.360520       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
E0712 02:55:26.361105       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""`

**Comment by Leweyy** [comment]
> @Leweyy Can you share the solution? I have same issue like this:
> 
> ```
> I0712 02:54:35.755452       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
> I0712 02:54:35.756354       1 main.go:190] "starting manager\n"
> I0712 02:54:35.849361       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:35.849430       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> I0712 02:54:37.008593       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:37.008632       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> I0712 02:54:37.514662       1 request.go:601] "Waited for 1.047725337s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/discovery.k8s.io/v1beta1?timeout=32s\n"
> I0712 02:54:39.463049       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:39.463088       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:41.360598       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> I0712 02:54:45.000032       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:45.000065       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:46.360354       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:54:51.360924       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:54:56.361243       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> I0712 02:54:57.789768       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:54:57.789800       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:55:01.360698       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:55:06.360650       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:55:11.360435       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:55:16.359860       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> I0712 02:55:20.027473       1 reflector.go:424] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:55:20.027504       1 reflector.go:140] "pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io \"secrets-store.csi.k8s.io\" is forbidden: User \"system:serviceaccount:kube-system:secrets-store-csi-driver\" cannot list resource \"csidrivers\" in API group \"storage.k8s.io\" at the cluster scope\n"
> E0712 02:55:21.360520       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> E0712 02:55:26.361105       1 secretproviderclasspodstatus_controller.go:97] "failed to patch secret owner ref" err="failed to list secret provider class pod status, err: no matches for kind \"SecretProviderClassPodStatus\" in version \"secrets-store.csi.x-k8s.io/v1\""
> ```

My issue was cause by me trying to deploy using terraform and the kubectl resource was missing out parts of the deployment
