### ISSUE TITLE
Caching support in the driver

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#1229]
- Supporting disconnected scenarios via caching
- This could potentially help with large clusters 

xref: https://docs.google.com/document/d/1zje84bP5bXoJJrn6GwpgLAeAhUoAjnb5zRE5Jzwwv5M/edit?usp=sharing

/kind feature

**Comment by aramase** [comment]
As there is no plan to implement an offline mode in the CSI driver, this issue is not relevant.

We can open a separate issue for caching in the driver to avoid provider throttling.

/close

**Comment by JorTurFer** [comment]
> As there is no plan to implement an offline mode in the CSI driver, this issue is not relevant.

Do you have more info about the decision? I've reviewed the google docs but I've not seen it. This would be awesome for scenarios where the upstream service isn't available due to provider errors. For example, if the Azure Key Vault service it's not available, workloads can be affected as no new pods will be scheduled despite of there are other pods with the same secrets
