### ISSUE TITLE
Service Account Token for CSI Driver

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#453]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Reference KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1855-csi-driver-service-account-token/README.md

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by micahhausler** [comment]
Based on my poking around, it looks like there are several changes required. First is a trivial addition of propagating the `csi.storage.k8s.io/serviceAccount.tokens` attribute in [`NodePublishVolume`](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/6f4f83631933c5ae984044df5f9922da2d30a49d/pkg/secrets-store/nodeserver.go#L102-L106).

The other part would be to add support for [`RequiresRepublish`](https://kubernetes-csi.github.io/docs/token-requests.html?search=#usage) when a token expires.

> If this is true, NodePublishVolume will be periodically called. When used with TokenRequest, the token will be refreshed if it expired. NodePublishVolume should only change the contents rather than the mount because container will not be restarted to reflect the mount change. The period between NodePublishVolume is 0.1s.

Based on my read, `NodePublishVolume()` [currently returns](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/6f4f83631933c5ae984044df5f9922da2d30a49d/pkg/secrets-store/nodeserver.go#L121-L124) if the token is already mounted, instead of propagating a fresh token on to the provider. My understanding is that the actual _mount(2)_ is [made in `NodePublishVolume`](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/6f4f83631933c5ae984044df5f9922da2d30a49d/pkg/secrets-store/nodeserver.go#L187), and the provider is responsible for writing the file content.

I'm guessing providers are relying on only being invoked once, but does re-invoking `provider.Mount()` break a contract with providers for an existing volume? I didn't see anything in the [protobuf spec doc comment](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/provider/v1alpha1/service.proto#L27-L28)  or the [documentation site](https://secrets-store-csi-driver.sigs.k8s.io/providers.html#implementation-details)

Even if there isn't an explicit contract, it might be safer to add another method on [`CSIDriverProvider`](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/provider/v1alpha1/service.proto#L21-L29), maybe something like. 
```protobuf
service CSIDriverProvider {
    // ... existing methods

    // Update the mount operation in the provider. Providers may receive updated
    // attributes or secrets.
    // Providers MUST atomically update files 
    rpc UpdateMount(MountRequest) returns (MountResponse) {}
}
```
That way providers could rely on previous call patterns, and could update the mount contents transparently based on refreshed tokens.

I'd be happy to pick up a PR for an initial stab this. I'm pretty new to this project and CSI in general, so please do correct me if I'm mistaken on this.
