### ISSUE TITLE
Propagation of NodePublishVolumeRequest.VolumeContext to providers

### ISSUE THREAD

**Issue by micahhausler** [kubernetes-sigs/secrets-store-csi-driver#475]
**Describe the solution you'd like**

I was wondering if it is intentional to filter out VolumeContext (Pod `.spec.volumes[].csi.volumeAttributes`) parameters passed on to providers by limiting the key to:

* `csi.storage.k8s.io/pod.name`
* `csi.storage.k8s.io/pod.namespace`
* `csi.storage.k8s.io/pod.uid`
* `csi.storage.k8s.io/serviceAccount.name`
* SecretProviderClass `.Spec.Parameters`

Is the pod creator considered untrusted? It might be convenient for providers to have access to `volumeAttributes` for per-volume metadata.

**Comment by aramase** [comment]
The volume attributes are user defined apart from the default ones added by kubelet. 

```bash
csi.storage.k8s.io/ephemeral:true 
csi.storage.k8s.io/pod.name:nginx-78cfc8db98-5s5rr 
csi.storage.k8s.io/pod.namespace:default 
csi.storage.k8s.io/pod.uid:9f88edc9-4b36-4405-9802-7aa621df338c 
csi.storage.k8s.io/serviceAccount.name:default 
secretProviderClass:testspc
```

The change should be minimal in `NodePublishVolume`. However we need to reconstruct these attributes in the rotation logic as rotation isn't invoked by kubelet. 

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/7f21cd32e4ff4f355b1a118fa80f60c8b59bbeb0/pkg/rotation/reconciler.go#L220-L224

If we explore the option of doing rotation based on the `requiresRepublish` and it's feasible, then we might be able to just rely solely on NodePublishVolume and pass the whole volume attributes as is to the provider.

**Comment by tam7t** [comment]
Based on some of the discussion on https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/585 we likely don't want plugins to _rely_ on having this information (since some may be missing during rotation requests) but that a good start is to pass all attributes on any real request.

IMO we should do this and close it once we pass all attributes, and work on #585 toward providing more attributes in a backwards-compatible way for the rotation feature.

/assign @aramase
