### ISSUE TITLE
Update metrics-addr to accept integer value rather than ':port-number'

### ISSUE THREAD

**Issue by nilekhc** [kubernetes-sigs/secrets-store-csi-driver#646]
User should not worry about formatting while providing port information. Code should handle necessary formatting (`:port-number` in this case). This also helps in avoiding helm template rendering [issues](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/614#discussion_r659839796).

**Comment by Atharva-Shinde** [comment]
hey can I work on this issue??

**Comment by Atharva-Shinde** [comment]
can you help me getting started ??

**Comment by MadhavJivrajani** [comment]
/assign @Atharva-Shinde 

@nilekhc please ensure enough context and pointers are provided for a good-first-issue :)
good-first-issues are typically zero-entry-barrier issues that folks with little to no background can pick up 😄 

---

Based on my understanding, the following would need to be done but please correct me if I've gotten it wrong since I'm not very privy to the codebase :)

- change `flag.String` to `flag.Int` and `:8095` to `8095` 
  https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/181f3bd87a2159df5d952e390a9e13068b753e36/cmd/secrets-store-csi-driver/main.go#L58
- add some form of logic here to convert `port` which would now be an `int` to `:port` which is a `string` here:
  https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/181f3bd87a2159df5d952e390a9e13068b753e36/cmd/secrets-store-csi-driver/main.go#L110-L113
  The `metricsAddr` would now be your modified string port 
- change all occurences of `metricsAddr` in [this](https://github.com/kubernetes-sigs/secrets-store-csi-driver/search?q=metricsAddr&type=) to have an `int`, i.e. `8095` and not `:8095`

It's possible I missed something, but this would be the general step by step approach I'd follow :)

**Comment by tam7t** [comment]
I'm not sure that I agree that this should be an integer value - the benefit of it being an address instead of just a port is that you can control listening i.e. `127.0.0.1:<port>` vs `0.0.0.0:<port>`

**Comment by nilekhc** [comment]
/close

ref : https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/704#issuecomment-921130931
