### ISSUE TITLE
deploy/secrets-store-csi-driver.yaml in tag 1.0.0 is referencing image: k8s.gcr.io/csi-secrets-store/driver:v1.0.0-rc.1?

### ISSUE THREAD

**Issue by deyanp** [kubernetes-sigs/secrets-store-csi-driver#837]
Why is 

https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v1.0.0/deploy/secrets-store-csi-driver.yaml

referencing 

image: k8s.gcr.io/csi-secrets-store/driver:v1.0.0-rc.1?

?

**Comment by deyanp** [comment]
I am referring to this file: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/v1.0.0/deploy/secrets-store-csi-driver.yaml

**Comment by nilekhc** [comment]
We are releasing v1.0.1 this week. These changes will be included in the new release tag.

**Comment by tam7t** [comment]
It looks like we tagged commit 91cd35b3c8f150e10be451547dabe96b442dd224 as v1.0.0, which seems to be on the `main` branch when I believe we intended to tag 407be391e05b3a58a6883d0b943764273b792a3f on the `release-1.0` branch.

As we do v1.0.1 tag this week let's see if we come across something in our release process that led to this mistake:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/docs/RELEASE.md

**Comment by tam7t** [comment]
Looking at diffs it seems the only difference in the `deploy/` section was the docker tag identified in this issue.

The diff on the docker image was just build script (`docker/Dockerfile`): https://github.com/kubernetes-sigs/secrets-store-csi-driver/compare/v1.0.0-rc.1...407be391e05b3a58a6883d0b943764273b792a3f

And that its most likely [step 6](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/aada382ac2054631ad215751be4baf81e8986100/docs/RELEASE.md) was accidentally performed against `main` instead of the `release-1.0` branch.

I believe helm installs should have received the correct versions.

**Comment by nilekhc** [comment]
> Looking at diffs it seems the only difference in the `deploy/` section was the docker tag identified in this issue.
> 
> The diff on the docker image was just build script (`docker/Dockerfile`): [v1.0.0-rc.1...407be39](https://github.com/kubernetes-sigs/secrets-store-csi-driver/compare/v1.0.0-rc.1...407be391e05b3a58a6883d0b943764273b792a3f)
> 
> And that its most likely [step 6](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/aada382ac2054631ad215751be4baf81e8986100/docs/RELEASE.md) was accidentally performed against `main` instead of the `release-1.0` branch.
> 
> I believe helm installs should have received the correct versions.

Thanks for analysis @tam7t. The new tag has the correct values now.

**Comment by deyanp** [comment]
great, thanks @nilekhc and @tam7t , I am closing this now
