### ISSUE TITLE
https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts 404 Not Found

### ISSUE THREAD

**Issue by fubar** [kubernetes-sigs/secrets-store-csi-driver#896]
The repo at https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts fails to load with 404. Looks like this has happened before https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/812

What causes it to go down and how can it be prevented from happening again?

**Comment by sozercan** [comment]
@fubar Helm charts are hosted in GitHub Pages. There's no `index.html` hosted in that url, that's why you are seeing a 404. Helm discovers charts using `index.yaml` which is hosted in https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts/index.yaml

Is `helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts` and `helm repo update` not working for you? If so, what's the error?

**Comment by fubar** [comment]
Got it, thanks, that works as expected.
