### ISSUE TITLE
failed to mount secrets store object content, provider not found: provider aws

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes-sigs/secrets-store-csi-driver#953]
**Describe the bug**
```
E0515 13:21:11.025544       1 nodeserver.go:235] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="myns/mypod-74679c49bf-f7trm"
I0515 13:21:11.025580       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/f5bcf484-9b77-4ccd-ac85-3319c8f7c1e1/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="myns/mypod-74679c49bf-f7trm"
```
I can't tell if this bug is related to `secrets-store-csi-driver-provider-aws` or to `secrets-store-csi-driver`

**To Reproduce**

1. Install `secrets-store-csi-driver` helm chart with `1.1.2` version
2. install `csi-secrets-store-provider-aws` helm chart with `0.0.2` version
3. create a pod with csi driver `secrets-store.csi.k8s.io` volume which injects a file to the pod

**Environment:**
Kubernetes EKS version v1.22.6-eks-14c7a48

**Additional context**

my pod describe logs
```
kubectl -n myns describe pod mypod-74679c49bf-f7trm

Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    11m                    default-scheduler  Successfully assigned myns/mypod-74679c49bf-f7trm to ip-10-102-60-11.ec2.internal
  Warning  FailedMount  5m37s                  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
  Warning  FailedMount  5m13s (x2 over 9m46s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[aws-iam-token secrets-store-inline kube-api-access-ttgwq]: timed out waiting for the condition
  Warning  FailedMount  92s (x12 over 11m)     kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod myns/mypod-74679c49bf-f7trm, err: error connecting to provider "aws": provider not found: provider "aws"
  Warning  FailedMount  42s (x3 over 7m30s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline kube-api-access-ttgwq aws-iam-token]: timed out waiting for the condition

```

csi-secrets-store-provider-aws logs
```
kubectl -n kube-system logs -f system-csi-secrets-store-provider-aws-fg7ff
I0504 10:23:46.572837       1 main.go:32] Starting secrets-store-csi-driver-provider-aws version 1.0.r2-2021.08.13.20.34
I0504 10:23:46.574142       1 main.go:77] Listening for connections on address: /etc/kubernetes/secrets-store-csi-providers/aws.sock
```

secrets-store-csi-driver node-driver-registrar logs
```
kubectl -n kube-system logs -f secrets-store-csi-driver-lvd28 -c node-driver-registrar
I0515 13:19:08.291404       1 main.go:166] Version: v2.5.0
I0515 13:19:08.291434       1 main.go:167] Running node-driver-registrar in mode=registration
I0515 13:19:08.291912       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0515 13:19:08.291935       1 connection.go:154] Connecting to unix:///csi/csi.sock
I0515 13:19:09.292814       1 main.go:198] Calling CSI driver to discover driver name
I0515 13:19:09.292843       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0515 13:19:09.292848       1 connection.go:184] GRPC request: {}
I0515 13:19:09.300057       1 connection.go:186] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v1.1.2"}
I0515 13:19:09.300149       1 connection.go:187] GRPC error: <nil>
I0515 13:19:09.300157       1 main.go:208] CSI driver name: "secrets-store.csi.k8s.io"
I0515 13:19:09.300341       1 node_register.go:53] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0515 13:19:09.300514       1 node_register.go:62] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0515 13:19:09.300652       1 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0515 13:19:09.608123       1 main.go:102] Received GetInfo call: &InfoRequest{}
I0515 13:19:09.608301       1 main.go:109] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/csi-secrets-store/registration"
I0515 13:19:09.650343       1 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

secrets-store-csi-driver secrets-store logs
```
kubectl -n kube-system logs -f secrets-store-csi-driver-lvd28 -c secrets-store
I0515 13:19:08.498123       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0515 13:19:08.499840       1 main.go:181] starting manager
I0515 13:19:08.600672       1 secrets-store.go:46] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.1.2" buildTime="2022-03-30-21:59"
I0515 13:19:08.600878       1 server.go:120] "Listening for connections" address="//csi/csi.sock"
I0515 13:19:09.609204       1 nodeserver.go:359] node: getting default node info
E0515 13:21:11.025544       1 nodeserver.go:235] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="myns/mypod-74679c49bf-f7trm"
I0515 13:21:11.025580       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/f5bcf484-9b77-4ccd-ac85-3319c8f7c1e1/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="myns/mypod-74679c49bf-f7trm"
E0515 13:23:13.066343       1 nodeserver.go:235] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="myns/mypod-74679c49bf-f7trm"
I0515 13:23:13.066374       1 nodeserver.go:81] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/f5bcf484-9b77-4ccd-ac85-3319c8f7c1e1/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="myns/mypod-74679c49bf-f7trm"
E0515 13:25:15.163767       1 nodeserver.go:235] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="myns/mypod-74679c49bf-f7trm"
```

more info:
The `SecretProviderClass` resource is in the same namespace like my pod

restart to secrets-store-csi-driver daemonset didn't help
```
kubectl -n kube-system rollout restart ds/secrets-store-csi-driver
```

**Comment by aramase** [comment]
Thanks for reporting the issue!

1. Can you share the output for `kubectl get ds/secrets-store-csi-driver -o yaml`?
2. Is there an aws provider pod running on the same node as the driver pod?

**Comment by dsaydon90** [comment]
Hi @aramase 

Thank you for your quick reply, here is the relevant information:

> Is there an aws provider pod running on the same node as the driver pod?

Yes, I'm using the `csi-secrets-store-provider-aws` [helm chart](https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws), which deploying the **aws provider** as daemonset.


> Can you share the output for kubectl get ds/secrets-store-csi-driver -o yaml

sure: 
```
kubectl get -n kube-system ds/secrets-store-csi-driver -o yaml

apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "8"
    meta.helm.sh/release-name: system
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-12-17T14:31:15Z"
  generation: 8
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.1.2
    helm.sh/chart: secrets-store-csi-driver-1.1.2
  name: secrets-store-csi-driver
  namespace: kube-system
  resourceVersion: "184780717"
  uid: a0084fdf-bde8-4c8d-bf66-8c5cbf081e92
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secrets-store-csi-driver
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: secrets-store
        kubectl.kubernetes.io/restartedAt: "2022-05-15T15:39:52+03:00"
      creationTimestamp: null
      labels:
        app: secrets-store-csi-driver
        app.kubernetes.io/instance: system
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: secrets-store-csi-driver
        app.kubernetes.io/version: 1.1.2
        helm.sh/chart: secrets-store-csi-driver-1.1.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-secrets-store/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-secrets-store/csi.sock
            - --mode=kubelet-registration-probe
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: node-driver-registrar
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        - --provider-volume=/etc/kubernetes/secrets-store-csi-providers
        - --additional-provider-volume-paths=/var/run/secrets-store-csi-providers
        - --metrics-addr=:8095
        - --provider-health-check-interval=2m
        - --max-call-recv-msg-size=4194304
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: k8s.gcr.io/csi-secrets-store/driver:v1.1.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        name: secrets-store
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        - containerPort: 8095
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /etc/kubernetes/secrets-store-csi-providers
          name: providers-dir
        - mountPath: /var/run/secrets-store-csi-providers
          name: providers-dir-0
      - args:
        - --csi-address=/csi/csi.sock
        - --probe-timeout=3s
        - --http-endpoint=0.0.0.0:9808
        - -v=2
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
        nodeGroup: gp
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: secrets-store-csi-driver
      serviceAccountName: secrets-store-csi-driver
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi-secrets-store/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /etc/kubernetes/secrets-store-csi-providers
          type: DirectoryOrCreate
        name: providers-dir
      - hostPath:
          path: /var/run/secrets-store-csi-providers
          type: DirectoryOrCreate
        name: providers-dir-0
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 5
  desiredNumberScheduled: 5
  numberAvailable: 5
  numberMisscheduled: 0
  numberReady: 5
  observedGeneration: 8
  updatedNumberScheduled: 5
```

It might be related to the `Listening for connections on address` path?
`aws provider` sock file path: `/etc/kubernetes/secrets-store-csi-providers/aws.sock`
while the `secrets-store-csi-driver` sock file path: /var/lib/kubelet/plugins/csi-secrets-store/csi.sock

**Comment by dsaydon90** [comment]
Hi @aramase ,

Thanks again for your answer, actually I don't have quotes on my provider's name, here is my `SecretProviderClass` resource:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    meta.helm.sh/release-name: global
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-12-17T14:40:38Z"
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-secret-class-name
  namespace: myns
  resourceVersion: "123456789"
  uid: 123456789
spec:
  parameters:
    objects: |
      - objectName: my-secret-name
        objectType: secretsmanager
        objectAlias: sec-file.json
    region: us-east-1
  provider: aws
```
Another idea that might help?

**Comment by aramase** [comment]
Can you share the output for `kubectl get pods -o wide` in the namespace where driver and provider pods are running?

**Comment by dsaydon90** [comment]
@aramase Sure:

```
kubectl -n myns get pod -o wide -A | grep ip-10-102-66-114.ec2.internal
NAME                                       READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
myns            mypod-7b8d74f6b-prdgn                                   0/2     ContainerCreating   0             71s     <none>          ip-10-102-66-114.ec2.internal   <none>           <none>
kube-system         secrets-store-csi-driver-nshbc                             3/3     Running             0             6d18h   10.102.82.207   ip-10-102-66-114.ec2.internal   <none>           <none>
kube-system         system-csi-secrets-store-provider-aws-rp57c                1/1     Running             0             17d     10.102.66.114   ip-10-102-66-114.ec2.internal   <none>           <none>
```

**Comment by aramase** [comment]
It does look like there is a driver and provider pod running on the node. Two things you can try:
1. Run with an older version of the driver (`v1.0.2`) which always uses `/etc/kubernetes/secrets-store-csi-providers` as the volume path for provider unix sockets, just to confirm if this is just an issue for you with the latest driver.
2. Try a clean install of the driver, provider and pod in a new cluster to see if you can repro.

As I mentioned, we are running the latest versions as part of CI today for driver and provider and haven't really seen any errors.

**Comment by dsaydon90** [comment]
Thank you @aramase , I did as you suggested, and I have downgraded into `1.0.1` version and it worked

**Comment by oliver-paul** [comment]
Hi Team

I am getting the same error. I was using Karpenter version 0.24 and I migrated to Version 0.33. The secrets were working fine  in Karpenter version 0.24. When I migrated to Version 0.33 started to get errors said below:

This is the csi-secret-store-csi-driver logs in the karpenter node:

I1226 14:04:51.563659       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I1226 14:04:51.565140       1 main.go:190] "starting manager\n"
I1226 14:04:51.666205       1 secrets-store.go:46] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.3.4" buildTime="2023-06-12-15:27"
I1226 14:04:51.666306       1 reconciler.go:130] "starting rotation reconciler" rotationPollInterval="2m0s"
I1226 14:04:51.669936       1 server.go:121] "Listening for connections" address="//csi/csi.sock"
I1226 14:04:52.419008       1 nodeserver.go:365] "node: getting default node info\n"
I1226 14:04:52.710066       1 request.go:601] "Waited for 1.046662105s due to client-side throttling, not priority and fairness, request: GET:https://10.100.0.1:443/apis/acme.cert-manager.io/v1?timeout=32s\n"
E1226 14:04:54.613645       1 nodeserver.go:242] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
I1226 14:04:54.613703       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1b7e5d01-1823-41dc-b153-f07589ea47fe/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
E1226 14:05:02.671636       1 nodeserver.go:242] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
I1226 14:05:02.671678       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1b7e5d01-1823-41dc-b153-f07589ea47fe/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
E1226 14:05:18.700947       1 nodeserver.go:242] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
I1226 14:05:18.701369       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1b7e5d01-1823-41dc-b153-f07589ea47fe/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
E1226 14:05:50.734133       1 nodeserver.go:242] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
I1226 14:05:50.734191       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1b7e5d01-1823-41dc-b153-f07589ea47fe/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
E1226 14:06:54.826658       1 nodeserver.go:242] "failed to mount secrets store object content" err="error connecting to provider \"aws\": provider not found: provider \"aws\"" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"
I1226 14:06:54.826695       1 nodeserver.go:88] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1b7e5d01-1823-41dc-b153-f07589ea47fe/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="scheduler/scheduler-deployment-859b8566b7-85w4z"

The Pod Events are 
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  5m14s                  default-scheduler  0/10 nodes are available: 10 node(s) didn't match Pod's node affinity/selector. preemption: 0/10 nodes are available: 10 Preemption is not helpful for scheduling..
  Normal   Nominated         5m13s                  karpenter          Pod should schedule on: nodeclaim/scheduler-thlqd
  Normal   Scheduled         4m40s                  default-scheduler  Successfully assigned scheduler/scheduler-deployment-859b8566b7-85w4z to ip-172-16-55-108.ec2.internal
  Warning  FailedMount       4m36s (x4 over 4m40s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
  Warning  FailedMount       30s (x6 over 4m32s)    kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod scheduler/scheduler-deployment-859b8566b7-85w4z, err: error connecting to provider "aws": provider not found: provider "aws"
  Warning  FailedMount       22s (x2 over 2m37s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
  
  Any idea what might be causing this issue?
